name: Docker Image test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag testimage
      - name: Test container output
        run: docker run --rm testimage --accept-license --accept-gdpr
